### ISSUE TITLE
Kubeflow: Notebooks with GPU cannot be scheduled because GPU nodes are not scaling up/down

### ISSUE THREAD

**Issue by ncbkr** [pluralsh/plural-artifacts#137]
## Summary

Via the Kubeflow Dashboard, I create a new notebook with GPU enabled (see screenshots below for my configuration). I expect to be able to connect to it after a few minutes.

Instead, the UI keeps indicating that the server is being provisioned. On the cluster, the pod stays in state "pending" and i see these events on the cluster: 

-   `0/5 nodes are available: 5 node(s) didn't match Pod's node affinity/selector.`
-   `pod didn't trigger scale-up: 8 node(s) had taint {plural.sh/capacityType: SPOT}, that the pod didn't tolerate, 13 node(s) didn't match Pod's node affinity`

## Reproduction

on an aws-based Plural Cluster with Kubeflow installed, try launching a new notebook with GPU enabled (see screenshots below)

## Dagit UI/UX Issue Screenshots
![image](https://user-images.githubusercontent.com/70146154/151962549-1347e7bc-a381-44d7-8f30-faa401d3cc2a.png)

![image](https://user-images.githubusercontent.com/70146154/151962583-99495a7a-8561-4a8c-bd44-e02724174146.png)

## Additional Info about Your Environment

Splitting this issue into a couple components:

- [ ] #141
- [x] #142
- [x] #143

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by DavidSpek** [comment]
Splitting this issue into a couple components:

- [ ] Create a managed node group for each availability zone
- [ ] Create a Terraform module for adding managed node groups
- [ ] Use new Terraform module in the Kubeflow app to create GPU managed node groups
