### ISSUE TITLE
Onboard cube.dev

### ISSUE THREAD

**Issue by michaeljguarino** [pluralsh/plural-artifacts#177]
## Use Case
cube.dev is a pretty promising analytics visualization solution that many users might find useful

## Ideas of Implementation
It looks like they don't have a working helm chart, but do have some k8s documentation already: https://cube.dev/docs/deployment/platforms/kubernetes

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by walkoss** [comment]
@ismaelheelio cube is onboarded!

**Comment by ismaelheelio** [comment]
Thanks Walid! Good job!
