### ISSUE TITLE
Updating Airbyte to v0.40.7

### ISSUE THREAD

**Issue by amrael** [pluralsh/plural-artifacts#353]
## Use Case
- Some connectors like GA4 are not included in the current version.
- Nearly a hundred connectors need to be updated right after it's installed.
- Airbyte does not import data from new versions, so it's not possible to migrate from other servers.

## Additional Info
https://github.com/airbytehq/airbyte/releases

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by skwaugh** [comment]
Please update Airbyte to v0.40.25

starting in 0.40.19 they released a new UI for quickly building new connectors.

**Comment by michaeljguarino** [comment]
This has been done
