### ISSUE TITLE
Onboard ray.io

### ISSUE THREAD

**Issue by michaeljguarino** [pluralsh/plural-artifacts#359]
## Use Case
hyperparameter tuning toolkit that can be useful for ML jobs

## Ideas of Implementation
https://docs.ray.io/en/latest/cluster/kubernetes/index.html

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by DavidSpek** [comment]
I've been investigating this as well.

**Comment by DavidSpek** [comment]
This has been onboarded :).
