### ISSUE TITLE
Support dagster user-agent

### ISSUE THREAD

**Issue by mjclarke94** [pluralsh/plural-artifacts#513]
## Use Case
For hybrid deployments of dagster, the orchestration plane is handled by Dagster, whilst the compute is managed by the customer on their own infrasturcture. There is a separate helm chart for this, but it is effectively a stripped back version of the full OSS dagster chart, with an additional pod running a user-agent.

It would be great to be able to support this kind of deployment  as well.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by michaeljguarino** [comment]
This is now available with the dagster-agent app on the marketplace!
