### ISSUE TITLE
Onboard Directus.io

### ISSUE THREAD

**Issue by qorbani** [pluralsh/plural-artifacts#536]
## Use Case

[Directus](https://directus.io/) is an open-source real-time API and App dashboard for managing SQL database content. It installs on top of any SQL database while you remain in complete control of your new or existing database. No need to migrate to a proprietary data model, so there's no vendor lock-in.

## Ideas of Implementation
There is already a community-driven [helm chart](https://github.com/directus-community/helm-chart) that can be used as a starting point. 

## Additional Info
[GitHub](https://github.com/directus/directus)
[Authentication](https://docs.directus.io/self-hosted/config-options.html#authentication)

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by michaeljguarino** [comment]
@qorbani thanks for the suggestion, we'll get it in line to add to the platform as soon as possible

**Comment by qorbani** [comment]
Thank you @michaeljguarino! 🙏 I'm a big fan of Directus and used it in many projects. If you guys can adopt it with your ODIC, that would be HUGE! Nevertheless, having it even without that would help many people.

**Comment by michaeljguarino** [comment]
@qorbani directus does work with plural oidc currently (we're also using it in prod on our new marketing website)
