### ISSUE TITLE
Bug: Elasticsearch chart

### ISSUE THREAD

**Issue by roicort** [pluralsh/plural-artifacts#636]
## Summary

While deploying elasticsearch the deploy halts with

**template: gotpl:4: function "base64decode" not defined**

## Reproduction

plural build --only elasticsearch && plural deploy 
--from elasticsearch --commit "rebuilding elasticsearch"   

## Additional Info about Your Environment

GCP Backend

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by michaeljguarino** [comment]
I think I see the bug, can you try now and see if it's fixed?

**Comment by roicort** [comment]
Awesome, @michaeljguarino. Fixed in[36bade2](https://github.com/pluralsh/plural-artifacts/commit/36bade2e33a23e3d5674fd4fa9fddc5484fef2a7)
